# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: telephonedirectory
services:
- name: gateway-webapi
  project: src/Global/Gateway.WebApi/Gateway.WebApi.csproj
  bindings:
    - protocol: http
      port: 44382
- name: telephonedirectory-saga
  project: src/Global/TelephoneDirectory.Saga/TelephoneDirectory.Saga.csproj
- name: telephonedirectory-auth
  project: src/Microservices/Csharp/Auth/TelephoneDirectory.Auth/TelephoneDirectory.Auth.csproj
  bindings:
    - protocol: http
      port: 44001
- name: telephonedirectory-guide
  project: src/Microservices/Csharp/Guide/TelephoneDirectory.Guide/TelephoneDirectory.Guide.csproj
  bindings:
    - protocol: http
      port: 44337
- name: telephonedirectory-report
  project: src/Microservices/Csharp/Report/TelephoneDirectory.Report/TelephoneDirectory.Report.csproj
  bindings:
    - protocol: http
      port: 44373
- name: guidedb
  image: postgres
  env:
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      value: admin
    - name: POSTGRES_DB
      value: PhoneGuide
  bindings:
    - port: 5432
- name: reportdb
  image: postgres
  env:
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      value: admin
    - name: POSTGRES_DB
      value: PhoneReport
  bindings:
    - port: 5433
- name: authdb
  image: mcr.microsoft.com/mssql/server:2019-latest
  env:
    - name: SA_PASSWORD
      value: Admin!23
    - name: ACCEPT_EULA
      value: 'Y'
  volumes:
    - name: authdb_volume
      target: /var/opt/mssql
  bindings:
    - port: 1453
      connectionString: Server=${host},${port};User Id=sa;Database=PhoneAuth;Password=${env:SA_PASSWORD};