name: telephonedirectory
extensions:
- name: dapr
  components-path: "./"
  services:
    telephonedirectory-guide:
      http-port: 7002
      grpc-port: 7003
    telephonedirectory-report:
      http-port: 8002
      grpc-port: 8003
      enabled: true
      
services:
- name: gateway-webapi
  project: src/Global/Gateway.WebApi/Gateway.WebApi.csproj
  bindings:
    - protocol: http
      port: 44382
- name: telephonedirectory-saga
  project: src/Global/TelephoneDirectory.Saga/TelephoneDirectory.Saga.csproj
- name: telephonedirectory-auth
  project: src/Microservices/Csharp/Auth/TelephoneDirectory.Auth/TelephoneDirectory.Auth.csproj
  bindings:
    - protocol: http
      port: 44001
- name: telephonedirectory-guide
  project: src/Microservices/Csharp/Guide/TelephoneDirectory.Guide/TelephoneDirectory.Guide.csproj
  bindings:
    - protocol: http
      port: 44337
- name: telephonedirectory-report
  project: src/Microservices/Csharp/Report/TelephoneDirectory.Report/TelephoneDirectory.Report.csproj
  bindings:
    - protocol: http
      port: 44373
- name: guidedb
  image: postgres
  env:
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      value: admin
    - name: POSTGRES_DB
      value: PhoneGuide
  bindings:
    - port: 5432
- name: reportdb
  image: postgres
  env:
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      value: admin
    - name: POSTGRES_DB
      value: PhoneReport
  bindings:
    - port: 5433
- name: authdb
  image: mcr.microsoft.com/mssql/server:2019-latest
  env:
    - name: MSSQL_SA_PASSWORD
      value: Admin!23
    - name: ACCEPT_EULA
      value: 'Y'
    - name: MSSQL_PID
      value: EnterpriseCore
  volumes:
    - name: authdb_volume
      target: /var/opt/mssql
  bindings:
    - port: 1433
      connectionString: Server=${host},${port};User Id=sa;Database=PhoneAuth;Password=${env:MSSQL_SA_PASSWORD};
- name: redis
  image: redis
  bindings:
    - port: 6379
      containerPort: 6379